version: '3.4'

services:
  vectormaster:
    image: vectormaster
    build:
      context: website
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
